name: System Health Check

on:
  schedule:
    - cron: '0 * * * *'  # Runs every hour
  workflow_dispatch:

jobs:
  health-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install psutil

      - name: Run Health Check
        run: |
          import shutil
          import psutil

          def check_disk_usage(disk):
              du = shutil.disk_usage(disk)
              free = du.free / du.total * 100
              return free > 20

          def check_memory_usage():
              mu = psutil.virtual_memory()
              free = mu.available / mu.total * 100
              return free > 20

          if __name__ == "__main__":
              if not check_disk_usage("/"):
                  print("ERROR: Not enough disk space")
              if not check_memory_usage():
                  print("ERROR: Not enough memory")
              print("Everything is OK!")
        shell: python
